pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: 14.16.0

- task: DownloadSecureFile@1
  displayName: 'Download secure file for frontend'
  inputs:
    secureFile: 'env-var.ts'

- task: DownloadSecureFile@1
  displayName: 'Download secure file for api'
  inputs:
    secureFile: .env

- task: CopyFiles@2
  displayName: 'Copy secure files'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: |
     env-var.ts
     .env
    TargetFolder: '$(Build.Repository.LocalPath)'

- script: |
   ls -l
   pwd
   npm install -g @angular/cli
   npm install
   ng build --prod
  displayName: 'Command Line Script'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: dist

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: drop